### ISSUE TITLE
Issue with external booking created trigger

### ISSUE THREAD

**Issue by langalex** [cobot/zapier#136]
Hi there, Cobot Team!

Scott here, reaching out from Zapier Support. One or more of our mutual customers has reported an issue with the External Booking Created Trigger on your integration.

Expected Behavior:

* The trigger should successfully run when a new external booking is created in Cobot.

User Current Experience (Actual Behavior):

* The user receives an error message indicating a hydration error in the Zapier app itself. This error occurs when the trigger is run, and persists even after attempting to replay the failed run.

Steps to Reproduce within Zapier Editor:

1. User creates a new external booking in Cobot.
2. The corresponding Zap is triggered in Zapier.
3. The Zap fails to run successfully, returning a hydration error.

Current Log GISTs/Screenshots:

- Error screenshot: ![Error screenshot](https://cdn.zapier.com/storage/photos/d428b278a0443fb5853ade673bba2cb2.png)
- Error log: [Error log](https://gists.security.zapier.com/gists/98be5f7b-a3f9-4bf7-9c1a-c1ff5c8c63c0)

Here's a log of a webhook that preceded the error:

* https://gists.security.zapier.com/gists/39bc5bc0-7b67-4a64-8ae2-877be4fc48cf

We noticed that the webhook's payload only includes one property—`url`—and does not include `id`.

I mention that because it looks like the trigger attempts to make a call after receiving the hook, but the last part of the path is `undefined`:

`404 GET [https://api.cobot.me/bookings/undefined`](https://api.cobot.me/bookings/undefined%60)

Here's a log of that request:

* https://gists.security.zapier.com/gists/78e4a6e8-201e-4307-a3b0-808fd42ef13e

Could you take a look and see what might be causing this not to work properly? The account they are using to connect to your service is: [hello@thecornercoworking.ca](mailto:hello@thecornercoworking.ca)

**Comment by markaeaton** [comment]
Hey @langalex this bug is causing all external booking triggers to fail. Any ETA for a fix? Thanks - Mark

**Comment by markaeaton** [comment]
Still no membership ID is sent with this trigger. 😞
