### ISSUE TITLE
Trigger 'MembershipConfirmed' missing data fields

### ISSUE THREAD

**Issue by markaeaton** [cobot/zapier#157]
MembershipConfirmed is missing the following fields, that were included in previous versions.

- All member address fields are missing
- Plan description
- Plan price per cycle
- Plan cancellation period
- Phone number
- Company name

**Screenshot does not show all missing fields, examples only**

<img width="513" alt="Screenshot 2024-08-02 at 9 20 15 PM" src="https://github.com/user-attachments/assets/31cae794-4fbb-4bed-bf38-7f602e28f667">

**Comment by Jsnxyz** [comment]
@wetterkrank Perhaps you could pick this up? 

The way this should be done is adding all the missing fields for `MembershipApiResponse` in `types/api-responses.d.ts`. 
Then formatting the fields as we'd like to show in zapier or keep it as it is for `MembershipOutput` in `types/output.d.ts`
Then actually adding the missing output fields in `utils/api-to.output.ts` on `apiResponseToMembershipOutput`
Adjust tests too.

**Comment by wetterkrank** [comment]
Done. 
@langalex, I've tested the new version 2.4.2 (private) in Zapier -- the requested membership fields are pulled as expected.
